USE hw5;

show TABLES;

desc INVOICE;

SELECT
    count(*)
FROM
    invoice;

SELECT
    count(DISTINCT CUS_CODE)
FROM
    CUSTOMER
WHERE
    CUS_BALANCE > 500;

SELECT
    CUS_CODE,
    INV_NUMBER,
    DATE_FORMAT (INV_DATE, '%d-%b%y'),
    P_DESCRIPT,
    LINE_UNITS,
    LINE_PRICE
FROM
    CUSTOMER
    NATURAL JOIN INVOICE
    NATURAL JOIN PRODUCT
    NATURAL JOIN LINE
ORDER BY
    CUS_CODE,
    INV_NUMBER,
    LINE_UNITS;

SELECT
    CUS_CODE,
    INV_NUMBER,
    SUM(LINE_UNITS * LINE_PRICE) as Invoice_Total
FROM
    CUSTOMER
    NATURAL JOIN INVOICE
    NATURAL JOIN LINE
GROUP BY
    CUS_CODE,
    INV_NUMBER;

SELECT
    C.CUS_CODE,
    C.CUS_BALANCE,
    SUM(L.LINE_UNITS * L.LINE_PRICE) AS TOTAL_PURCHASE
FROM
    CUSTOMER C
    NATURAL JOIN INVOICE I
    NATURAL JOIN LINE L
GROUP BY
    C.CUS_CODE;

SELECT
    C.CUS_CODE,
    C.CUS_BALANCE,
    SUM(L.LINE_UNITS * L.LINE_PRICE) AS TOTAL_PURCHASE,
    COUNT(L.LINE_NUMBER) AS number_of_purchase
FROM
    CUSTOMER C
    NATURAL JOIN INVOICE I
    NATURAL JOIN LINE L
GROUP BY
    C.CUS_CODE;

SELECT
    INV_NUMBER,
    SUM(L.LINE_UNITS * L.LINE_PRICE) as Invoice_Total
FROM
    `INVOICE`
    NATURAL JOIN `LINE` L
GROUP BY
    `INV_NUMBER`;